###
# Global settings
###

CXX=g++
CXXFLAGS=-std=c++14

.PHONY: all
all: allcfgs

###
# Configure generators
###

CFG__hasparam = 
CFG__hasparam_sc2 = scale=2.0

###
# Include common support Makefile
###

include /home/alexreinking/test_programs/hlgen/support/Makefile

